from __future__ import annotations

import json
from pathlib import Path
from .models import AuditResult, SubmissionStatus, ComponentStatus, Severity, Finding, Action
from .preflight import run_preflight
from .structure_detector import detect_components
from .reference_engine import analyze_references
from .table_engine import analyze_tables
from .consistency_checker import check_internal_consistency
from .word_formatter import format_document
from .report_generator import generate_report
from .ooxml_utils import count_page_fields_by_part


def _dedupe_findings(findings):
    seen=set();out=[]
    for f in findings:
        key=(f.code,f.message)
        if key not in seen:out.append(f);seen.add(key)
    return out


def audit_document(input_path: str|Path, output_dir: str|Path, language: str="en", write_outputs: bool=True) -> AuditResult:
    input_path=Path(input_path);out=Path(output_dir);out.mkdir(parents=True,exist_ok=True)
    pre=run_preflight(input_path)
    comps,sfind,metadata=detect_components(input_path)
    refs,rfind=analyze_references(input_path,pre.footnotes_present)
    tables,tfind=analyze_tables(input_path)
    cfind=check_internal_consistency(input_path)
    findings=sfind+rfind+tfind+cfind
    if pre.duplicate_page_fields:
        findings.append(Finding("DUPLICATE_PAGE_FIELDS","Duplicate PAGE fields detected","More than one PAGE field exists in at least one header/footer part. The formatter can safely retain one and remove duplicates when formatting is permitted.",Severity.MAJOR,Action.AUTO_FIX))
    page_field_parts=count_page_fields_by_part(input_path)
    header_page_fields=sum(v for k,v in page_field_parts.items() if "header" in k)
    footer_page_fields=sum(v for k,v in page_field_parts.items() if "footer" in k)
    if footer_page_fields and not header_page_fields:
        findings.append(Finding(
            "PAGE_FIELD_LOCATION_NONCOMPLIANT",
            "Page numbering is in the footer",
            "PAGE field(s) were detected in footer part(s), while the Narxoz student-paper guidance places the page number in the right-aligned header. The v0.2 formatter preserves this rather than moving pagination when section linkage may be ambiguous; student/manual review is required.",
            Severity.MAJOR,Action.MANUAL_REVIEW,
            evidence={"footer_page_fields":footer_page_fields,"header_page_fields":header_page_fields}
        ))
    if pre.automatic_numbering_paragraphs:
        findings.append(Finding("AUTOMATIC_WORD_NUMBERING_DETECTED","Automatic Word numbering detected",f"Detected Word numbering metadata (numId/style numbering) on {len(pre.automatic_numbering_paragraphs)} paragraph(s). These paragraphs are not treated as unnumbered merely because the visible number may be generated by Word.",Severity.ADVISORY,Action.FLAG))
    missing=sum(1 for c in comps.values() if c.critical and c.applicable and c.status==ComponentStatus.MISSING)
    if missing>2:
        status=SubmissionStatus.RESUBMIT
    else:
        unresolved=any(c.status!=ComponentStatus.PRESENT_COMPLIANT for c in comps.values() if c.applicable) or any(f.severity in {Severity.CRITICAL,Severity.MAJOR} and f.action!=Action.AUTO_FIX for f in findings)
        status=SubmissionStatus.CONDITIONAL if unresolved else SubmissionStatus.READY
    audit=AuditResult(str(input_path),language,status,missing,comps,pre,refs,tables,_dedupe_findings(findings),metadata=metadata)
    if write_outputs:
        stem=input_path.stem
        if status!=SubmissionStatus.RESUBMIT:
            formatted=out/f"{stem}_FORMATTED_DISSERTATION.docx"
            audit.auto_fixes=format_document(input_path,formatted,refs.system);audit.formatted_path=str(formatted)
        report_name=f"{stem}_NONCOMPLIANCE_REPORT.docx" if status==SubmissionStatus.RESUBMIT else f"{stem}_COMPLIANCE_REPORT.docx"
        report=out/report_name;generate_report(audit,report);audit.report_path=str(report)
        with open(out/f"{stem}_audit.json","w",encoding="utf-8") as f:json.dump(audit.to_dict(),f,ensure_ascii=False,indent=2)
    return audit
